name: Brew TestBot

on:
  push:
    branches:
      - main
  pull_request:

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_GITHUB_ACTIONS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  test-bot:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: true
          cask: false
          test-bot: true

      - run: brew test-bot --only-cleanup-before

      - name: Set up RubyGems cache
        shell: bash
        run: |
          cache_key_prefix="${{ runner.os }}"
          if [[ "${{ runner.os }}" = macOS ]]
          then
            macos_full_version="$(sw_vers -productVersion)"
            macos_version="${macos_full_version%%.*}"
            arch="$(uname -m)"
            cache_key_prefix="${macos_version}-${arch}"
          fi
          echo "cache_key_prefix=${cache_key_prefix}" >> "$GITHUB_ENV"

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ env.cache_key_prefix }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ env.cache_key_prefix }}-rubygems-

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax

      - run: brew test-bot --only-formulae
        if: github.event_name == 'pull_request'

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@main
        with:
          name: bottles
          path: '*.bottle.*'
